### ISSUE TITLE
Crashes when trying to build src directory

### ISSUE THREAD

**Issue by AronT-TLV** [yeghishe/scala-aws-lambda-seed.g8#1]
I issued the following command at the command line:
`sbt new yeghishe/scala-aws-lambda-seed.g8`

And this is what happens
```
This is a seed project to create AWS Lambdas in Sala and upload to 
S3. 

name [scala-aws-lambda-seed]: em-scala-lambda-nbo
organization [io.github.yeghishe]: com.emelai
package [com.emelai.emscalalambdanbo]: 
sbt_version [maven(com.typesafe.sbt, sbt-interface, stable)]: stable
scala_version [maven(org.scala-lang, scala-dist, stable)]: org.scala-lang
ficus_version [maven(com.iheart, ficus_2.12, stable)]: ficus_2.12
scala_mock_version [maven(org.scalamock, scalamock-scalatest-support_2.12, stable)]: scalamock-scalatest-support_2.12
lambda_utils_version [maven(io.github.yeghishe, scala-aws-lambda-utils_2.12, stable)]: scala-aws-lambda-utils_2.12
lambda_events_version [maven(com.amazonaws, aws-lambda-java-events, stable)]: aws-lambda-java-events

Exiting due to error in the template
File: /var/folders/8n/tjbg015149bf86w2y0kn9b3c0000gp/T/giter8-374938732891866/src/main/g8/README.md, context [anonymous] 3:1 internal error: org.stringtemplate.v4.compiler.STException: context [anonymous] 3:1 attribute description isn't defined
	at giter8.G8$STErrorHandler.runTimeError(g8.scala:110)
	at giter8.G8$STErrorHandler.runTimeError(g8.scala:105)
	at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:193)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
...
```

Looking at directory this is what was created:
```
Nefertiti:em-scala-lambda-nbo aront$ ls -al
total 40
drwxr-xr-x@ 8 aront  staff   272 Jul  9 10:20 .
drwxr-xr-x@ 4 aront  staff   136 Jul  9 10:20 ..
-rw-r--r--@ 1 aront  staff    24 Jul  9 10:20 .gitignore
-rw-r--r--@ 1 aront  staff   315 Jul  9 10:20 .scalafmt.conf
-rw-r--r--@ 1 aront  staff   126 Jul  9 10:18 .travis.yml
-rw-r--r--@ 1 aront  staff   520 Jul  9 10:20 LICENSE
-rw-r--r--@ 1 aront  staff  1458 Jul  9 10:20 build.sbt
drwxr-xr-x@ 4 aront  staff   136 Jul  9 10:20 project
```

I realize this isn't production code - I'll go try the activator, but just thought to share...

**Comment by andyczerwonka** [comment]
I am seeing the same problem.
